services:
  portfolio:
    image: seankelley-porfolio
    build: .
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
